gui:
  windowSize: normal
  scrollHeight: 8
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
keybinding:
  commits:
    moveDownCommit: '<c-J>' # move commit down one
    moveUpCommit: '<c-K>' # move commit up one
